import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { QueryClientProvider } from '@/components/query-client-provider';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/lib/auth';
import { ApiClientProvider } from '@/components/api-client-provider';
import { ToastContainer, ToastProvider } from 'the-omelet-ui/toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider session={session}>
          <ApiClientProvider>
            <QueryClientProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <ToastProvider>
                  {children}
                  <ToastContainer />
                </ToastProvider>
              </ThemeProvider>
            </QueryClientProvider>
          </ApiClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
